### ISSUE TITLE
Anyone tried with a Wemos D1 mini?

### ISSUE THREAD

**Issue by lorenzofattori** [DaAwesomeP/dmxusb#10]
I'm trying to run the simple and fastled example with a wemos D1 mini without any succes.
I changed the pinout to be able to drive the LED_INBUILT or pin D2 for the fastled but no response at all from dmx. I tried both Enttec and DMXKing emulation.

I'm trying with both Freestyler DMX: 
- Enttec: no USB-DMX found
- DMXking: no response

and Chamsys in Enttec mode

any idea where to start looking? anyone tried with the wemos d1 before?

thanks
Lorenzo

**Comment by DaAwesomeP** [comment]
Hi @lorenzofattori,
I apologize for the late response. I am not familiar with Freestyler DMX, but that is probably the issue. This library will not cause your Arduino-compatible device to be detected as an Enttec or DMXking device. Spoofing detection as another device is a bad practice. What this library does is receive the same commands and protocol that an Enttec or DMXking device receives. Does Freestyler DMX allow you to select Enttec or DMXking and force selection of a serial port?

If there is no way to force Freestyler DMX to try to connect to a serial port in Enttec or DMXking mode, then you will need to use OLA (open lighting architecture) as a proxy of sorts. OLA will allow you to define a device in it my serial port. You can then map the device to sACN or Artnet with OLA.

However, because the Arduino in question is WiFi-enabled, you may be more interested in a library that will connect directly by sACN or Artnet over WiFi. This may or may not be easier depending on your experience with sACN, Artnet, and the ESP8266.

I'm going to close this for now since it probably isn't an issue with the library, but I will reopen it if it is.

I'm going to close this since it

**Comment by lorenzofattori** [comment]
Thank you for the clarification, both software unfortunately don't allow to select which interface to use, Freestyler only looks for FTDI chips (my esp has chinese usb/serial converter), Chamsys has no settings at all, automatic detection.
Because the library is not emulating the enttec interface in detection then this is definetly the problem.

As you said, I will go with Artnet over WiFi, my idea was to have a 2in1 tool capable to handle Artnet and USB.

Thank you
