### ISSUE TITLE
Suggested controller/adaptor software?

### ISSUE THREAD

**Issue by mikepurvis** [DaAwesomeP/dmxusb#17]
I'm trying to set up some generic addressable LEDs for use, ultimately, with Lumia Stream via a Teensy. This firmware seems like a good starting point, as it allows the Teensy to emulate a USB DMX controller, and Lumia can talk to that, I guess via QLC+ and a LoopMIDI port (as suggested in [this video](https://www.youtube.com/watch?v=-xEn1HHF_as)).

So far, I have validated the basic serial connectivity just using [ultraDMX Configuration](https://dmxking.com/downloads-list), however this just seems to be a test utility, not at an actual passthru. I'm also trying QLC+, but it doesn't seem able to see the serial device (in my case COM4) in order to do anything with it:

![image](https://user-images.githubusercontent.com/944666/181821195-134ea90c-2830-49ee-a0eb-b45eec8c4d7d.png)

I haven't made it to OLA yet as I'm hoping to avoid having to run a whole VM just for this one piece of the puzzle. Is there something obvious I'm missing here as far as an easy way to bridge the gap from USB serial device to MIDI in Windows? Maybe it's as easy as giving the Teensy a VID/PID that QLC will recognize as ones of its supported devices?

**Comment by DaAwesomeP** [comment]
My sincere apologies for the delayed response!

I really like QLC+ for testing things like this, but it has always had one flaw. The issue that you're seeing with QLC+ is most likely that it expects only a FTDI-based serial to USB adapter (which all of the Enttec and Enttec-like devices use), but the Teensy does not use FTDI or similar adapters; it uses the native USB port and a standard USB serial implementation (I believe CDC ACM). Unfortunately changing the VID/PID won't do the trick unless you can also replicate the FTDI USB protocol, which is probably not worth it (and possibly legally precarious).

Yeah, OLA would be my first recommendation, but you're on Windows so that's definitely more annoying for OLA. You could potentially use Docker (I'm very certain this will work) or WSL (also should work fine) pretty easily. Or you could get a separate TTL FTDI adapter for the Teensy. Though I think there is a better solution for your particular case.

If you are OK skipping QLC+, then the best solution would be to not use this library at all. The Teensy can very easily instead show up as a USB MIDI device that you can use directly with your software of choice. See the "receiving" sections here: [Teensyduino: Using USB MIDI with Teensy on the Arduino IDE](https://www.pjrc.com/teensy/td_midi.html). There is an example showing how to control an LED with a MIDI note. You can use either MIDI notes or the control parameters. This is outside the scope of this library, but I'm happy to help anyway I can :grinning:.

As a side note, it looks like Lumia Stream supports MIDI, OSC, and Artnet. OLA can convert all of those things to the Enttec USB serial protocol and is very reliable should you wish to do that.

**Comment by mikepurvis** [comment]
No worries on the delay, as a fellow open-source maintainer, I expect nothing and appreciate anything at all, much less such a detailed and thoughtful response.

I did actually see that the Teensy could be a native MIDI device and played briefly with it already, but it seems like the light behaviour authoring story directly in Lumia was going to be extremely painful— its "MIDI" support appears to be limited to just triggering note X at velocity Y, which seems to be more geared toward like a one-off spotlight or something rather than having any kind of understanding of RGB or the spatial relationship between pixels (to do chaser patterns or whatever). I think I was picturing that QLC+ might be the answer to the authoring side, but honestly I'm kind of new to both these tools.

I guess another way to do it is just assign six notes to be RGB and alt-RGB, and then have others that can be triggered to "play" specific patterns of the two selected colors. Certainly my preference would have been to have the firmware part be as thin as possible and have basically all the smarts be on the computer side, but that may just not be workable.

**Comment by DaAwesomeP** [comment]
Another option that I just thought of would be use to something like [Processing](https://processing.org/) as a gateway between either Lumia or QLC+ and DMXUSB. There would be some programming involved, but it would be minimal and all running on your computer. I have used the OSC library in Processing extensively, and I am certain it would receive data from QLC+ or Lumia just fine. I have not tried the Artnet library, but I am sure it is fine as well. There is also a library for connecting to Enttec-like devices, which should theoretically work perfectly to send data to a DMXUSB device. I have not used it, but I am mostly certain it is not tied to FTDI drives. So the possible patterns are:
```
Lumia --OSC--> QLC+ --OSC--> Processing --USB serial--> DMXUSB
```
or
```
Lumia --OSC--> Processing --USB Serial--> DMXUSB
```

Processing is more than capable of outright replacing QLC+ as well should you wish to. It is a programming environment designed for creative visual applications. You can either run it headless or make use of the visualization capabilities.

I would also recommend using OSC or Artnet since Lumia supports it. That way you don't need to deal with any loopback MIDI devices.

**Comment by DaAwesomeP** [comment]
Going to close this for now since it is not really a fixable issue with DMXUSB, but please continue the conversation as this is a fascinating problem to solve that will maybe be useful to others in the future. :grin:
