### ISSUE TITLE
Doesn't seem to work with maizedmx

### ISSUE THREAD

**Issue by emeraldtip** [DaAwesomeP/dmxusb#18]
I may just be extremely stupid, but I can't seem to get it working with maizedmx. I set the com port to the arduino uno and enabled serial, but nothing. On QLC it's not detected and I can't figure out how to use it. 
The chip and port definitely work as I have tested it with just a simple dmxsimple program.
Help would be appreciated.

**Comment by DaAwesomeP** [comment]
Hi there @emeraldtip,

Please see the first large paragraph in this response: https://github.com/DaAwesomeP/dmxusb/issues/17#issuecomment-1205869441

In short, to use QLC+ you either need either:

- An Arduino with an FTDI module (the UNO uses a different serial chip)
- An adapter service to Artnet/sACN like the Open Lighting Architecture that does not care about the type of USB serial interface
- An external FTDI module for your Arduino

**Comment by tonyxforce** [comment]
>  (the UNO uses a different serial chip)
which FTDI (which if i understand correctly is just a USB-UART converter) should i(t) use?

**Comment by DaAwesomeP** [comment]
@tonyxforce which Arduino are you using? Correct, the FTDI is just a USB-UART, but it is a specific one. Some applications/software are able to work with any serial port while others look specifically for a FTDI device. Since the official Arduino UNO does not have a FTDI USB-UART onboard you can use an external one connected to the `RX` and `TX` pins. If you are on Linux or Mac I would recommend OLA as well.

It sounds like you're starting a new project! Feel free to open a new issue if you need any more help!

**Comment by tonyxforce** [comment]
Doesn't arduino unos have a builtin FTDI chip for flashing (clones have the ch340g chip, the originals the atmega16u2)?

**Comment by DaAwesomeP** [comment]
> Doesn't arduino unos have a builtin FTDI chip for flashing (clones have the ch340g chip, the originals the atmega16u2)?

Yes, all of the UNOs (ATmega328 main MCU) have a USB-UART device of some sort. They all function the same; the issue is what the software on the computer end is looking for. While most software that interact with Arduino simply look for a serial port of any sort, many pieces of software designed to work with ENTTEC DMX adapters look _specifically_ for a FTDI device. I have not used MaizeDMX myself but from @emeraldtip's intial question it sounds like it only supports FTDI devices.

**Comment by tonyxforce** [comment]
> While most software that interact with Arduino simply look for a serial port of any sort, many pieces of software designed to work with ENTTEC DMX adapters look _specifically_ for a FTDI device.

How does the software know the difference between an FTDI chip in (clone)arduinos and external usb to uart converters?

**Comment by DaAwesomeP** [comment]
> How does the software know the difference between an FTDI chip in (clone)arduinos and external usb to uart converters?

If they are using the FTDI-specific API (which only works with FTDI devices and not all USB UART devices), then they will only be able to connect to FTDI devices. They can either connect to the USB device directly or use a driver from the OS that shows up as a specific FTDI device (not a general serial port). The FTDI API or driver almost certainly checks the USB VID and PID before connecting to a device (all USB devices uses these to identify the manufacturer and product of the device).

These pieces of software are probably not using operating system's abstraction for serial ports (`COMX` on Windows, `/dev/ttyUSBX` or `/dev/ttyACMX` or Linux/Mac). Since they are looking at the USB or driver level and not the OS serial level, they care about which device they connect to.
