### ISSUE TITLE
What Lighting software are compatible with this library on Arduino?

### ISSUE THREAD

**Issue by ginopc** [DaAwesomeP/dmxusb#19]
Freestyler or Qlc+ not detect my interface. I based my circuit from #[this](https://i.pinimg.com/originals/30/91/f0/3091f05b365a26b6eb31e55ad5f30a21.png) sketch and DMXUSB_DMXSimple.
I connect RX and TX ports to MAX485 A and B channels, but I don't understand why code specify channel 3 for DMX.

**Comment by DaAwesomeP** [comment]
> Freestyler or Qlc+ not detect my interface.

I should really add this to the readme. You need a FTDI serial interface or an Arduino with one built in (must be specifically FTDI). See https://github.com/DaAwesomeP/dmxusb/issues/17#issuecomment-1205869441 and https://github.com/DaAwesomeP/dmxusb/issues/18#issuecomment-1276287214

> I connect RX and TX ports to MAX485 A and B channels, but I don't understand why code specify channel 3 for DMX.

To be honest I have not tried this example myself. The [DmxSimple documentation](https://github.com/PaulStoffregen/DmxSimple#dmxsimpleusepinpin) makes me think that `usePin()` is unnecessary here.

Note that you will need to control the `~RE` and `DE` pins on the MAX485. They both need to be high to output/transmit RS485 (instead of receiving). You could just tie them both to the 3.3V rail instead of digital or analog pins.

**Comment by bennigraf** [comment]
Hey!

I hope you don't mind me chiming in here. I'm trying to make this work with an Arduino Nano (328p, "old bootloader"). I'm using this simplified sketch for now:

```
#include "DMXUSB.h"

// DMXUSB should receive and transmit data at the highest, most reliable speed possible
// Recommended Arduino baud rate: 115200
// Recommended Teensy 3 baud rate: 2000000 (2 Mb/s)
// DMX baud rate: 250000
// MIDI baud rate: 31250
#define DMXUSB_BAUDRATE 115200

// receive a DMX transmission
void myDMXCallback(int universe, char buffer[512]) {
  for (int index=0; index < 512; index++) { // for each channel, universe starts at 0
    int channel = index + 1; // channel starts at 0, so index 0 is DMX channel 1 and index 511 is DMX channel 512
    int value = buffer[index]; // DMX value 0 to 255
    if (universe == 0 && channel == 1) {
      digitalWrite(LED_BUILTIN, value > 127 ? HIGH : LOW);
    }
  }
}

DMXUSB myDMXUsb(
  // Stream serial,
  Serial,
  // int baudrate,
  DMXUSB_BAUDRATE,
  // int mode,
  0,
  // void (*dmxInCallback)(int universe, unsigned int index, char buffer[512])
  myDMXCallback,
  // universes
  1,
  // id?
  0x1ffffffa
);

void setup() {
  Serial.begin(DMXUSB_BAUDRATE);
  while (!Serial) {
    ; // wait for serial port to connect. Needed for native USB port only
  }

  pinMode(LED_BUILTIN, OUTPUT);
}

void loop() {
  myDMXUsb.listen();
}
```

Should this "just work"? Open Lighting Architecture/`olad` sees the USB port, but doesn't recognize the device (`USB Widget didn't respond to messages, esta id 0, device id 0`). QLC+ recognizes it as a "dump" ftdi device and shoves data to it, but the arduino doesn't react as expected (I'm guessing it's the wrong data format). I did try various settings for the baud rate and `mode`. If you have any hints on this, I'd appreciate! 

Best, 
Benjamin.

**Comment by bennigraf** [comment]
Hey there,

by now, after some more debugging and tinkering, I found out that ola just needs more time to detect the device. If I increase the (hardcoded) timeout for the USB discovery phase from 200ms to 1200ms there, the Arduino Nano running DMXUSB with the code above is being recognized as Enttec compatible USB device :-). (I guess the Arduino just needs a little time to get the serial interface going and whatnot...)

I'd leave this info and the post above here for future reference, if that's ok.

Best,
Benjamin.

**Comment by DaAwesomeP** [comment]
Hi Benjamin @bennigraf,

I'm interested in why the Arduino took so long to respond to OLA. That shouldn't really be the case.

I think the issue is the `while (!Serial) {}` block. The ATmega328 does not have a native USB port (there is a serial to USB chip on the ATmega328-based development boards), so this loop could just be waiting a while and then timing out and finally continuing. I have not tried this myself but that is my guess.

May you try removing that block and letting me know if OLA works with the default 200ms? Additionally, where in the OLA source are you modifying this timeout?

Thanks!
Perry

**Comment by bennigraf** [comment]
Hi Perry!

Removing the `while (!Serial) {}` didn't make any difference unfortunately. I didn't find a clear explanation of whether it's needed or not (seems to depend on the board type), so I tried both ways. 

I did send a mail to the OLA mailing list with more details on the timeout changes: https://groups.google.com/g/open-lighting/c/6bhk62UrFf4 – it's in `WidgetDetectorThread.h:76ff`:

```
explicit WidgetDetectorThread(NewWidgetHandler *widget_handler,
                                  ola::io::SelectServerInterface *ss,
                                  unsigned int usb_pro_timeout = 1200,
                                                                 ^^^
                                  unsigned int robe_timeout = 200);
```

However, I found another explanation, which I'll copy from there: 

> I found out that initiating a serial connection towards the Arduino via USB always resets the device and makes it go through the bootloader again – this takes a considerate amount of time, which I didn't measure myself, but some people on the internet talk about 1-2 seconds. However I was able to program that Arduino Nano with just the DMXUSB "simplest" example without the bootloader (using another Arduino as programmer/ISP). In this mode, olad recognizes the device without any changes/within the original time limit of 200ms.

> So the problem is the Arduino bootloader delay; the solution is to remove the bootloader. Increasing the timeout value as suggested (or make it configurable) is probably not worth it with this solution at hand. I'll just have it documented here for now :-).

What do you think about mentioning this in the readme of this repository (which would be a simpler solution than patching OLA)? I could create a PR for that if you want.

And finally, since the topic of this issue is kinda open anyways, let me mention that I found out that the baudrate in ola is hardcoded to 115200 (I guess most other Enttec-compatible device on the market just use that as a default) – so make sure to set it like that when you want to use this library with ola.

Best and thanks,
Benjamin.

**Comment by DaAwesomeP** [comment]
> I did send a mail to the OLA mailing list with more details on the timeout changes: https://groups.google.com/g/open-lighting/c/6bhk62UrFf4 – it's in `WidgetDetectorThread.h:76ff`:

Ah, sorry I missed that! Sometimes Google Groups goes to spam in my inbox.

The bootloader bit is interesting. When I originally wrote the library I was testing with an Arduino Mega and a Teensy 3.2. I'm surprised that I never encountered this, but it makes sense. I do agree this is more of a DMXUSB/Arduino issue than an OLA issue since OLA follows the Enttec specification (though I don't remember if they specify a timeout).

> What do you think about mentioning this in the readme of this repository (which would be a simpler solution than patching OLA)? I could create a PR for that if you want.

That would be great! Please feel free to open a PR!

> And finally, since the topic of this issue is kinda open anyways, let me mention that I found out that the baudrate in ola is hardcoded to 115200 (I guess most other Enttec-compatible device on the market just use that as a default) – so make sure to set it like that when you want to use this library with ola.

Yes and no. It depends on the devices on both ends. OLA will dictate opening a serial port with 115200 baud, but some software-/MCU-defined USB serial ports (like Teensy) do not actually support the OS changing the baud rate and force the OS to use what it is given (so OLA's preference is ignored). For the Arduino Nano and similar boards that have separate USB to serial chips the baud rate of the USB serial chip is adjusted by the OS. In that case the Arduino's serial pins must match with how the OS sets the USB serial chip.
